services:
  - type: web
    name: omo-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install --no-audit --no-fund && npm run build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://omo-backend.onrender.com
    routes:
      - type: rewrite
        source: /api/*
        destination: https://omo-startup-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
